# Projects About  numpy Library

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

In [4]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [5]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [7]:
arr = np.array([[1.1,2.2,3.3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1.1 2.2 3.3]
 [4.  5.  6. ]]
2


In [8]:
arr = np.array([[[1,2,3],[4,5,6] ,[7,8,9],[10,11,12]]])

print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3


In [9]:
arr = np.array([1,2,3,5], ndmin=5)

print(arr)
print('number of dimnsion :', arr.ndim)

[[[[[1 2 3 5]]]]]
number of dimnsion : 5


In [10]:
arr = np.array([1,2,3,5], ndmin=15)

print(arr)
print('number of dimnsion :', arr.ndim)

[[[[[[[[[[[[[[[1 2 3 5]]]]]]]]]]]]]]]
number of dimnsion : 15


In [11]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('2nd element on 1st row:', arr[0, 1])

2nd element on 1st row: 20


In [12]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('4th element on 1st row:', arr[0, 3])

4th element on 1st row: 40


In [13]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('1st element on 2nd row:', arr[1, 0])

1st element on 2nd row: 60


In [14]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print('first element of 1st row: ', arr[0, 0])
print('last element of 2nd row: ', arr[1,4])
print("sum is" , arr[0, 0]+arr[1, 4])

first element of 1st row:  10
last element of 2nd row:  100
sum is 110


In [15]:
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:")
print(array1)

print("\n2D Array:")
print(array2)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Element-wise addition
add = array1 + array2

# Element-wise multiplication
multiply = array1 * array2

# Dot product
dot_product = np.dot(array1, array2)

print("Element-wise Addition:")
print(add)

print("\nElement-wise Multiplication:")
print(multiply)

print("\nDot Product:")
print(dot_product)


Element-wise Addition:
[6 6 6 6 6]

Element-wise Multiplication:
[5 8 9 8 5]

Dot Product:
35


In [17]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping array
reshaped = array.reshape((3, 2))

# Transposing array
transposed = array.T

print("Original Array:")
print(array)

print("\nReshaped Array (3x2):")
print(reshaped)

print("\nTransposed Array:")
print(transposed)


Original Array:
[[1 2 3]
 [4 5 6]]

Reshaped Array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [18]:
import numpy as np

# Random float numbers between 0 and 1
random_floats = np.random.rand(5)

# Random integers between 0 and 10
random_ints = np.random.randint(0, 10, 5)

print("Random Floats:")
print(random_floats)

print("\nRandom Integers:")
print(random_ints)


Random Floats:
[0.40209594 0.87571117 0.16865513 0.07234709 0.80947524]

Random Integers:
[2 7 7 8 1]


In [19]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(array)

# Standard deviation
std_dev = np.std(array)

# Sum
sum_array = np.sum(array)

print("Mean:")
print(mean)

print("\nStandard Deviation:")
print(std_dev)

print("\nSum:")
print(sum_array)


Mean:
5.5

Standard Deviation:
2.8722813232690143

Sum:
55


In [20]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Elements greater than 5
greater_than_five = array[array > 5]

print("Elements Greater Than 5:")
print(greater_than_five)


Elements Greater Than 5:
[ 6  7  8  9 10]


In [21]:
import numpy as np

# Creating matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.dot(matrix1, matrix2)

# Determinant
det = np.linalg.det(matrix1)

# Inverse
inverse = np.linalg.inv(matrix1)

print("Matrix Product:")
print(matrix_product)

print("\nDeterminant:")
print(det)

print("\nInverse:")
print(inverse)


Matrix Product:
[[19 22]
 [43 50]]

Determinant:
-2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimension is ", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [25]:
c = np.array([[[[1,2,3], [52,78,96], [78,96,52]]]])
print(c)
print("the dimension is", c.ndim)
d = c.flatten() 
print(d)
print("now the new dimension is", n.ndim)


[[[[ 1  2  3]
   [52 78 96]
   [78 96 52]]]]
the dimension is 4
[ 1  2  3 52 78 96 78 96 52]
now the new dimension is 1


In [26]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Min-max normalization
normalized_data = (data - np.min(data, axis=0)) / (np.max(data, axis=0) - np.min(data, axis=0))

print("Normalized Data:")
print(normalized_data)


Normalized Data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [27]:
import numpy as np

data = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# Replace NaNs with the mean of the column
col_mean = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_mean, inds[1])

print("Data with NaNs replaced:")
print(data)


Data with NaNs replaced:
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [28]:
import numpy as np

# Simulated time series data
time_series = np.random.randn(100)

# Moving average
window_size = 5
moving_avg = np.convolve(time_series, np.ones(window_size)/window_size, mode='valid')

print("Moving Average of Time Series:")
print(moving_avg)



Moving Average of Time Series:
[ 0.46872632  0.45624032  0.42891376  0.44810329  0.28070679  0.12132185
 -0.06510615 -0.12426836 -0.14092006 -0.78406536 -0.67442415 -0.83205932
 -0.60917671 -0.78095126 -0.22741351 -0.28409692  0.14475168 -0.30647051
 -0.01403285  0.15118171  0.04287053 -0.0860862   0.11037261  0.14560514
  0.07985162  0.284921    0.32842914  0.05797421 -0.139147   -0.16519174
 -0.02742686 -0.15937847  0.0109284   0.01838152  0.21204196 -0.02984842
  0.12953925  0.21916399  0.37380053 -0.00573056  0.04778455 -0.15197048
 -0.04849898  0.02048926  0.03989199  0.04045309  0.15345186  0.10793017
 -0.28727108 -0.4012311  -0.45892087 -0.39073457 -0.21517698 -0.00963704
  0.11821211  0.31476885  0.75606466  0.31317717  0.54689736  0.55552804
  0.43160774 -0.30545558 -0.02650057 -0.73015914 -0.87369199 -0.66124993
 -0.44701374 -0.06004823  0.34482402  0.43789761  0.29242459  0.590795
 -0.02578031  0.29699992  0.32773593  0.31447295  0.14623955  0.4535418
 -0.04457614  0.0698326

In [29]:
import numpy as np

# Element-wise operations using vectorization
large_array = np.random.rand(1000000)
result = large_array * 2 + 3

print("Result of Vectorized Operation:")
print(result[:10])  # Displaying only the first 10 elements for brevity


Result of Vectorized Operation:
[4.60155023 4.7316612  3.7825399  3.20989046 3.75138284 4.19489122
 4.99576022 3.13050265 4.73229566 4.85427706]


In [31]:
import numpy as np

def kmeans(X, k, max_iters=100):
    # Randomly initialize the centroids
    centroids = X[np.random.choice(X.shape[0], k, replace=False)]

    for _ in range(max_iters):
        # Compute distances from each point to each centroid
        distances = np.linalg.norm(X[:, np.newaxis] - centroids, axis=2)
        # Assign clusters based on closest centroid
        labels = np.argmin(distances, axis=1)
        # Compute new centroids as the mean of points in each cluster
        new_centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])
        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids

    return centroids, labels

# Simulated data
data = np.random.rand(100, 2)

# Apply k-means clustering
centroids, labels = kmeans(data, k=3)

print("Centroids of clusters:")
print(centroids)

print("\nLabels of each point:")
print(labels)


Centroids of clusters:
[[0.30170116 0.2827347 ]
 [0.32924246 0.83222743]
 [0.81817329 0.52257669]]

Labels of each point:
[1 1 1 0 1 2 0 2 2 0 2 1 1 0 0 2 0 1 0 1 0 0 2 2 0 0 2 0 0 0 2 2 0 0 1 0 0
 2 0 2 2 0 2 1 1 1 0 2 0 2 2 1 0 2 2 2 2 2 2 2 1 1 2 2 2 1 0 0 2 1 1 0 0 1
 2 2 1 2 2 1 2 0 1 1 2 0 0 0 1 1 0 1 2 1 0 1 2 0 2 2]


In [32]:
import numpy as np

# Simulated daily closing prices of a stock
closing_prices = np.random.rand(100) * 100

# Calculate daily returns
daily_returns = (closing_prices[1:] - closing_prices[:-1]) / closing_prices[:-1]

# Calculate volatility (standard deviation of returns)
volatility = np.std(daily_returns)

print("Daily Returns:")
print(daily_returns)

print("\nVolatility:")
print(volatility)


Daily Returns:
[ 3.13223714e+00  3.14254426e+00  1.00780147e+00 -6.90320731e-01
  4.32425360e+00 -9.71036750e-01  3.21200831e+01 -5.22058012e-01
 -8.36213132e-01  9.94131222e+00 -9.60717778e-01  3.27882935e+01
 -5.55405392e-01 -2.08700704e-01 -4.16355844e-01  2.87656058e+00
 -3.05310859e-01  8.10250738e-01 -2.31260663e-01  1.23409644e-01
 -1.58992396e-01 -1.83535563e-01  1.27602203e-01 -3.74403571e-01
 -5.83558347e-01  1.33918866e+00  1.55318505e+00 -9.48845510e-01
  2.53250729e+00  1.87043567e+00  5.11690631e-01 -7.23861353e-01
 -9.25914779e-01  4.31074333e+01 -7.88346874e-01 -5.04172779e-01
  6.08118295e+00 -1.48710987e-01  9.01397870e-01 -1.70706700e-01
 -3.98093866e-01 -5.54553668e-01 -7.70926130e-01  2.04457457e+01
 -6.16567054e-02 -5.22627982e-01 -9.73437050e-02 -4.34047669e-01
  1.16632672e+00 -4.39464950e-01  1.06463217e+00 -2.27839473e-01
 -5.34829216e-01  3.55757880e+00 -8.43678075e-01  3.07734564e+00
 -3.47264508e-01  1.71083480e+00 -2.94610403e-01  1.65844092e-02
  6.980455

In [33]:
import numpy as np

# Simulated data
data = np.random.rand(100, 3)

# Save to a file
np.save('data.npy', data)

# Load from a file
loaded_data = np.load('data.npy')

print("Loaded Data:")
print(loaded_data)


Loaded Data:
[[0.55154497 0.13634215 0.53635193]
 [0.44845265 0.092907   0.61178061]
 [0.99528108 0.70099765 0.02787907]
 [0.61331733 0.85869023 0.39725174]
 [0.86815574 0.72917259 0.16799151]
 [0.15770153 0.01372324 0.6787915 ]
 [0.02307722 0.93397675 0.69757604]
 [0.33899595 0.25894711 0.24049416]
 [0.7789669  0.89294861 0.40009791]
 [0.07391939 0.06059724 0.0071726 ]
 [0.00576885 0.27634386 0.58301805]
 [0.63098493 0.94478633 0.6310856 ]
 [0.57236741 0.04531027 0.19491793]
 [0.23763231 0.69092518 0.86355908]
 [0.03817916 0.1533996  0.72427823]
 [0.1385593  0.84400339 0.18947646]
 [0.55594111 0.57549009 0.73096641]
 [0.54024235 0.57295308 0.36675511]
 [0.01222485 0.04522267 0.77992039]
 [0.3954929  0.97667965 0.64123486]
 [0.74080448 0.50276254 0.06356031]
 [0.20849905 0.71116738 0.72801285]
 [0.42611232 0.70138194 0.54263793]
 [0.49782419 0.34424113 0.52852576]
 [0.6209086  0.53493544 0.43883858]
 [0.70071511 0.50669295 0.67906771]
 [0.68057463 0.30973707 0.44597499]
 [0.98371029 0.